CREATE TABLE [dbo].[Excel_Prep] (
    [ProductTypeID]               INT             NOT NULL,
    [Code]                        VARCHAR (50)    NOT NULL,
    [Name]                        VARCHAR (100)   NOT NULL,
    [PositionValue]               INT             NULL,
    [CreatedBy]                   INT             NULL,
    [CreateDate]                  DATETIME2 (3)   NULL,
    [ModifiedBy]                  INT             NULL,
    [ModifiedDate]                DATETIME2 (3)   NULL,
    [LastValue]                   VARCHAR (100)   NULL,
    [InitTransferLogID]           INT             NULL,
    [TransferLogID]               INT             NULL,
    [IsActive]                    SMALLINT        NULL,
    [SKUType]                     INT             NOT NULL,
    [ConversionValue]             DECIMAL (18, 4) NULL,
    [UNIT]                        VARCHAR (200)   NULL,
    [SIZE]                        VARCHAR (200)   NULL,
    [RetailUnitOfMeasure]         VARCHAR (50)    NULL,
    [PackUnitOfMeasure]           VARCHAR (50)    NULL,
    [PackNetWeightInKG]           DECIMAL (18, 4) NULL,
    [PackGrossWeightInKG]         DECIMAL (18, 4) NULL,
    [CurrentFreeOnBoardListPrice] DECIMAL (18, 4) NULL,
    [CurrentCustomCIF]            DECIMAL (18, 4) NULL,
    [CurrentWareHouseCIF]         DECIMAL (18, 4) NULL,
    [CurrentTradePrice]           DECIMAL (18, 4) NULL,
    [StockAlarmInPcs]             MONEY           NULL,
    [StockAlarmInCtn]             MONEY           NULL,
    [AverageDailySales]           MONEY           NULL,
    [MajorGroupId]                INT             NULL,
    [IsInventory]                 SMALLINT        NULL,
    [BarCode]                     NCHAR (50)      NULL,
    [BrandID]                     INT             NOT NULL,
    [Weight]                      MONEY           NULL,
    [WeightUnit]                  VARCHAR (100)   NULL,
    [AccountsPrice]               MONEY           NULL,
    [AveragePerdayConsumption]    MONEY           NULL,
    [ImportTime]                  INT             NULL,
    [ImportPrice]                 MONEY           NULL,
    [ShelfLife]                   MONEY           NULL,
    [Padding]                     MONEY           NULL,
    [InventoryTakeType]           VARCHAR (100)   NULL,
    [LatestPrice]                 MONEY           NULL,
    [IsSaleable]                  BIT             NULL,
    [HOSTTSellingPrice]           MONEY           NULL
);


GO

