CREATE TABLE [dbo].[PeriodicConsumptionItems] (
    [Id]                                               INT             IDENTITY (1601, 1) NOT NULL,
    [WarehouseConsumptionId]                           INT             NOT NULL,
    [PeriodicConsumptionId]                            INT             NOT NULL,
    [InventoryItemId]                                  INT             NOT NULL,
    [InventoryItemName]                                NVARCHAR (4000) NULL,
    [UnitName]                                         NVARCHAR (4000) NULL,
    [UnitMultiplier]                                   NUMERIC (16, 2) NOT NULL,
    [InStock]                                          DECIMAL (16, 4) NULL,
    [Purchase]                                         DECIMAL (16, 4) NULL,
    [Consumption]                                      DECIMAL (16, 4) NULL,
    [PhysicalInventory]                                DECIMAL (16, 4) NULL,
    [Cost]                                             DECIMAL (16, 4) NULL,
    [StockIn]                                          DECIMAL (16, 4) CONSTRAINT [DF_PeriodicConsumptionItems_StockIn] DEFAULT ((0)) NULL,
    [StockOut]                                         DECIMAL (16, 4) CONSTRAINT [DF_PeriodicConsumptionItems_StockOut] DEFAULT ((0)) NULL,
    [Wastage]                                          DECIMAL (16, 4) NULL,
    [ReturnAmount]                                     DECIMAL (16, 4) NULL,
    [StockTake]                                        DECIMAL (16, 4) NULL,
    [Remarks]                                          NVARCHAR (4000) NULL,
    [BatchInfo]                                        NVARCHAR (MAX)  NULL,
    [BatchInfoWhileWorkPeriodEnd]                      NVARCHAR (MAX)  NULL,
    [InStockValue]                                     DECIMAL (18, 4) NULL,
    [PurchaseValue]                                    DECIMAL (18, 4) NULL,
    [Production]                                       DECIMAL (18, 4) NULL,
    [ProductionValue]                                  DECIMAL (18, 4) NULL,
    [ConsumptionValue]                                 DECIMAL (18, 4) NULL,
    [PhysicalInventoryValue]                           DECIMAL (18, 4) NULL,
    [StockInValue]                                     DECIMAL (18, 4) NULL,
    [StockOutValue]                                    DECIMAL (18, 4) NULL,
    [WastageValue]                                     DECIMAL (18, 4) NULL,
    [ReturnAmountValue]                                DECIMAL (18, 4) NULL,
    [StockTakeValue]                                   DECIMAL (18, 4) NULL,
    [ConsumptionCarryForward]                          DECIMAL (18, 4) NULL,
    [ConsumptionCarryForwardValue]                     DECIMAL (18, 4) NULL,
    [StockOutCarryForward]                             DECIMAL (18, 4) NULL,
    [StockOutCarryForwardValue]                        DECIMAL (18, 4) NULL,
    [WastageCarryForward]                              DECIMAL (18, 4) NULL,
    [WastageCarryForwardValue]                         DECIMAL (18, 4) NULL,
    [ReturnAmountCarryForward]                         DECIMAL (18, 4) NULL,
    [ReturnAmountCarryForwardValue]                    DECIMAL (18, 4) NULL,
    [NegativeStockAdjustmentCarryForward]              DECIMAL (18, 4) NULL,
    [NegativeStockAdjustmentCarryForwardValue]         DECIMAL (18, 4) NULL,
    [ProductionPurposeCarryForward]                    DECIMAL (18, 4) NULL,
    [ProductionPurposeCarryForwardValue]               DECIMAL (18, 4) NULL,
    [NegativeStockAdjustment]                          DECIMAL (18, 4) NULL,
    [NegativeStockAdjustmentValue]                     DECIMAL (18, 4) NULL,
    [PositiveStockAdjustment]                          DECIMAL (18, 4) NULL,
    [PositiveStockAdjustmentValue]                     DECIMAL (18, 4) NULL,
    [ClosingStock]                                     DECIMAL (18, 4) NULL,
    [ClosingStockValue]                                DECIMAL (18, 4) NULL,
    [Produced]                                         DECIMAL (18, 4) NULL,
    [ProducedValue]                                    DECIMAL (18, 4) NULL,
    [PreviousNegativeStockAdjustmentCarryForward]      DECIMAL (18, 4) NULL,
    [PreviousWastageCarryForward]                      DECIMAL (18, 4) NULL,
    [PreviousReturnAmountCarryForward]                 DECIMAL (18, 4) NULL,
    [PreviousNegativeStockAdjustmentCarryForwardValue] DECIMAL (18, 4) NULL,
    [PreviousWastageCarryForwardValue]                 DECIMAL (18, 4) NULL,
    [PreviousReturnAmountCarryForwardValue]            DECIMAL (18, 4) NULL,
    [EODConsumptionCF]                                 DECIMAL (18, 4) NULL,
    [EODWastageCF]                                     DECIMAL (18, 4) NULL,
    [EODReturnAmountCF]                                DECIMAL (18, 4) NULL,
    [EODProductionPurposeCF]                           DECIMAL (18, 4) NULL,
    [EODStockOutCF]                                    DECIMAL (18, 4) NULL,
    [EODNegativeStockAdjustmentCF]                     DECIMAL (18, 4) NULL,
    [LatestPrice]                                      DECIMAL (18, 4) DEFAULT ((0)) NULL,
    CONSTRAINT [PK_dbo.PeriodicConsumptionItems] PRIMARY KEY CLUSTERED ([Id] ASC, [WarehouseConsumptionId] ASC, [PeriodicConsumptionId] ASC),
    CONSTRAINT [FK_dbo.PeriodicConsumptionItems_dbo.WarehouseConsumptions_PeriodicConsumptionId_WarehouseConsumptionId] FOREIGN KEY ([PeriodicConsumptionId], [WarehouseConsumptionId]) REFERENCES [dbo].[WarehouseConsumptions] ([Id], [PeriodicConsumptionId]) ON DELETE CASCADE
);


GO

CREATE NONCLUSTERED INDEX [IX_PeriodicConsumptionId_WarehouseConsumptionId]
    ON [dbo].[PeriodicConsumptionItems]([PeriodicConsumptionId] ASC, [WarehouseConsumptionId] ASC);


GO

