CREATE FUNCTION [SQL#].[Date_Format]
(@TheDate DATETIME NULL, @DateTimeFormat NVARCHAR (4000) NULL, @Culture NVARCHAR (10) NULL)
RETURNS NVARCHAR (4000)
AS
 EXTERNAL NAME [SQL#].[DATE].[Format]


GO

