CREATE FUNCTION [SQL#].[String_PadRight]
(@StringValue NVARCHAR (MAX) NULL, @StringWidth INT NULL, @PadCharacter NVARCHAR (4000) NULL)
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [SQL#].[STRING].[PadRight]


GO

