CREATE FUNCTION [SQL#].[String_Cut]
(@StringValue NVARCHAR (MAX) NULL, @Delimiter NVARCHAR (4000) NULL, @Fields NVARCHAR (4000) NULL)
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [SQL#].[STRING].[Cut]


GO

